// Copyright 2024–2026 Yardenah / Turkana Nation. MIT license.
//
// Record-invariant regressions (TRK-003 / ADR-0006):
//   • BUG-005: use() must reject metadata that was tampered with while the
//     stored AAD was preserved, and must never call unwrap in that case.
//   • Record identity: a record whose embedded ID differs from the requested
//     ID must be rejected.
//   • BUG-008: the decoder must reject trailing bytes and truncation.
//
// Test material only: fixed passphrase and generated bytes, nothing secret is
// printed. Assertions report error classes and call counts, never key bytes.

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:pqkeystore/pqkeystore.dart';

/// Wraps [inner] and counts how often the facade reaches the crypto adapter.
class _SpyCrypto implements PqKeystoreCrypto {
  _SpyCrypto(this.inner);

  final PqKeystoreCrypto inner;

  int wrapCalls = 0;
  int unwrapCalls = 0;

  @override
  Future<
    ({
      Uint8List ciphertext,
      Uint8List nonce,
      String wrapAlg,
      Map<String, dynamic>? kdfParams,
    })
  >
  wrap(Uint8List plaintext, Uint8List aad, UnlockMethod unlock) {
    wrapCalls++;
    return inner.wrap(plaintext, aad, unlock);
  }

  @override
  Future<Uint8List> unwrap(
    Uint8List ciphertext,
    Uint8List aad,
    Uint8List? nonce,
    String wrapAlg,
    UnlockMethod unlock, [
    Map<String, dynamic>? kdfParams,
  ]) {
    unwrapCalls++;
    return inner.unwrap(ciphertext, aad, nonce, wrapAlg, unlock, kdfParams);
  }
}

KeyMetadata _meta({
  required String id,
  KeyKind kind = KeyKind.mlKemSecret,
  String algorithm = 'ML-KEM-768',
  String? purpose = 'test',
  DateTime? createdAt,
}) => KeyMetadata(
  id: KeyId(id),
  kind: kind,
  algorithm: algorithm,
  createdAt: createdAt ?? DateTime.utc(2025, 1, 1),
  purpose: purpose,
);

Uint8List _passphrase() =>
    Uint8List.fromList(utf8.encode('test-only-passphrase'));

Uint8List _material() => Uint8List.fromList(List.generate(32, (i) => i));

void main() {
  late _SpyCrypto spy;
  late MemoryKeystoreBackend backend;
  late PqKeystore keystore;

  setUp(() {
    spy = _SpyCrypto(StubKeystoreCrypto());
    backend = MemoryKeystoreBackend();
    keystore = PqKeystore(backend: backend, crypto: spy);
  });

  /// Stores a valid record under [id] through the facade so the AAD is the
  /// canonical encoding of the metadata.
  Future<void> seed(String id) async {
    final result = await keystore.put(
      _meta(id: id),
      _material(),
      PassphraseUnlock(_passphrase()),
    );
    expect(result, isA<KsSuccess<void>>());
  }

  /// Rewrites the stored record with [metadata] while keeping the stored AAD,
  /// ciphertext, nonce and KDF parameters — the tamper shape BUG-005 describes.
  Future<void> retagPreservingAad(KeyId id, KeyMetadata metadata) async {
    final stored = await backend.getSealed(id);
    expect(stored, isNotNull);
    await backend.putSealed(
      id,
      SealedRecord(
        metadata: metadata,
        wrapAlg: stored!.wrapAlg,
        ciphertext: stored.ciphertext,
        aad: stored.aad,
        nonce: stored.nonce,
        kdfParams: stored.kdfParams,
      ),
    );
  }

  Future<KsResult<int>> useInt(KeyId id) =>
      keystore.use(id, PassphraseUnlock(_passphrase()), (p) async => p.length);

  group('BUG-005: use() re-validates the record before unwrap', () {
    test('an untampered record still unwraps', () async {
      await seed('invariant-valid');
      final result = await useInt(const KeyId('invariant-valid'));
      expect(result, isA<KsSuccess<int>>());
      expect((result as KsSuccess<int>).value, 32);
      expect(spy.unwrapCalls, 1);
    });

    test('metadata changed while the stored AAD is preserved is rejected', () async {
      await seed('invariant-tamper');
      await retagPreservingAad(
        const KeyId('invariant-tamper'),
        _meta(id: 'invariant-tamper', purpose: 'attacker'),
      );

      final result = await useInt(const KeyId('invariant-tamper'));

      expect(result, isA<KsFailure<int>>());
      expect((result as KsFailure<int>).error, isA<FormatError>());
      expect(
        spy.unwrapCalls,
        0,
        reason: 'unwrap must not be invoked for a record that fails validation',
      );
    });

    test('every authenticated metadata field is covered', () async {
      await seed('invariant-fields');

      final mutations = <String, KeyMetadata>{
        'kind': _meta(id: 'invariant-fields', kind: KeyKind.hybridKeyset),
        'algorithm': _meta(id: 'invariant-fields', algorithm: 'ML-KEM-1024'),
        'purpose': _meta(id: 'invariant-fields', purpose: 'other'),
        'createdAt': _meta(
          id: 'invariant-fields',
          createdAt: DateTime.utc(2030, 6, 1),
        ),
      };

      for (final mutation in mutations.entries) {
        await retagPreservingAad(
          const KeyId('invariant-fields'),
          mutation.value,
        );
        spy.unwrapCalls = 0;

        final result = await useInt(const KeyId('invariant-fields'));

        expect(
          result,
          isA<KsFailure<int>>(),
          reason: 'mutating ${mutation.key} must be rejected',
        );
        expect(
          spy.unwrapCalls,
          0,
          reason: '${mutation.key}: unwrap must not be invoked',
        );
      }
    });

    test('a record whose embedded ID differs from the requested ID is rejected',
        () async {
      await seed('invariant-identity');
      await retagPreservingAad(
        const KeyId('invariant-identity'),
        _meta(id: 'invariant-someone-else'),
      );

      final result = await useInt(const KeyId('invariant-identity'));

      expect(result, isA<KsFailure<int>>());
      expect((result as KsFailure<int>).error, isA<FormatError>());
      expect(spy.unwrapCalls, 0);
    });

    test('a missing record is still NotFound, not a format error', () async {
      final result = await useInt(const KeyId('invariant-absent'));
      expect(result, isA<KsFailure<int>>());
      expect((result as KsFailure<int>).error, isA<NotFound>());
      expect(spy.unwrapCalls, 0);
    });
  });

  group('BUG-008: strict decoder framing', () {
    late Uint8List encoded;

    setUp(() async {
      await seed('invariant-framing');
      final stored = await backend.getSealed(const KeyId('invariant-framing'));
      expect(stored, isNotNull);
      encoded = stored!.encode();
    });

    test('a valid record round-trips', () {
      final decoded = SealedRecord.decode(encoded);
      expect(decoded.metadata.id, const KeyId('invariant-framing'));
      expect(decoded.aad, SealedRecord.decode(encoded).aad);
    });

    test('a single appended byte is rejected', () {
      expect(
        () => SealedRecord.decode(Uint8List.fromList([...encoded, 0x00])),
        throwsA(isA<FormatException>()),
      );
    });

    test('a longer suffix is rejected', () {
      final padded = Uint8List.fromList([...encoded, ...List.filled(64, 0xAA)]);
      expect(
        () => SealedRecord.decode(padded),
        throwsA(isA<FormatException>()),
      );
    });

    test('truncation at field boundaries is rejected', () {
      for (final cut in [4, 8, 12, encoded.length - 1, encoded.length ~/ 2]) {
        expect(
          () => SealedRecord.decode(encoded.sublist(0, cut)),
          throwsA(isA<FormatException>()),
          reason: 'truncation at $cut must be rejected',
        );
      }
    });

    test('an absurd declared field length is rejected without a range error', () {
      // Field length lives at offset 8 (first length prefix after magic+version).
      final hostile = Uint8List.fromList(encoded);
      final view = ByteData.sublistView(hostile);
      view.setUint32(8, 0xFFFFFFFF, Endian.big);
      expect(
        () => SealedRecord.decode(hostile),
        throwsA(isA<FormatException>()),
      );
    });

    test('an unsupported version is rejected', () {
      final hostile = Uint8List.fromList(encoded);
      ByteData.sublistView(hostile).setUint32(4, 2, Endian.big);
      expect(
        () => SealedRecord.decode(hostile),
        throwsA(isA<FormatException>()),
      );
    });
  });
}
